name: test2
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
        - name: SMSE
          run: echo -n "${{ secrets.OCI_PRIVATE_KEY_FILENAME }}" >> foo && cut -c1-3 foo && cut -c4
      
